<?php

namespace Velygotsky\BaseBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * AdvertRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BaseRepository extends EntityRepository
{

}
